baseurl: "https://www.firstbonds.co.za"

title      : evo First Bonds – Bond Origination and Home Loan Experts
email      : martinsf0448@gmail.com
description: Let evo First Bonds get you the best deal on your homeloan and provide you with comparative quotes. Trust us to secure your bond finance. Many buyers choose us to manage their homeloans with the best rates..
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: xxx

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]